#!/bin/sh
# PreToolUse[Edit|Write|NotebookEdit] guard: deny hand-edits of GENERATED files
# (.claude/CLAUDE.md: "data/ and the renderer's public/{sprites,heroes}/ are generated").
# The sync script writes via Bash/node, so pipelines are unaffected — only direct
# tool edits are blocked. Adapted from the tbh-wiki guard for the standalone layout.
command -v jq >/dev/null 2>&1 || {
  # Fail to "ask", never open: without jq we cannot parse the call, so escalate to the human.
  printf '%s' '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"ask","permissionDecisionReason":"guard-generated-files.sh: jq not found - cannot inspect the edit; review it manually."}}'
  exit 0
}
input=$(cat)
file=$(printf '%s' "$input" | jq -r '.tool_input.file_path // .tool_input.notebook_path // ""')
[ -z "$file" ] && exit 0

root="${CLAUDE_PROJECT_DIR:-$(pwd)}"
rel="$file"
case "$rel" in
  "$root"/*) rel="${rel#"$root"/}" ;;
esac

deny() {
  jq -cn --arg reason "$1" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$reason}}'
  exit 0
}

case "$rel" in
  app/src/shared/data/*)
    deny "app/src/shared/data/ is synced from /data by app/scripts/sync-data.mjs — extend that script (or fix /data) and re-run the sync instead of hand-editing (app/CLAUDE.md)." ;;
  app/src/renderer/public/sprites/*|app/src/renderer/public/heroes/*)
    deny "app/src/renderer/public/{sprites,heroes}/ is generated by app/scripts/sync-data.mjs from /data — never hand-edit; extend the sync script instead (app/CLAUDE.md)." ;;
esac
exit 0
