import heroesData from "../../../shared/data/heroes.json";
import skillsData from "../../../shared/data/skills.json";
import stagesData from "../../../shared/data/stages.json";
import itemsMinData from "../../../shared/data/items-min.json";
import chestsMinData from "../../../shared/data/chests-min.json";
import { boxLevel } from "../../../shared/chest-boxes";
// Stage→box + the route's box list live in shared/ (the main process keys cooldowns by box too);
// re-exported here so renderer code keeps importing chest facts from one place (game-data).
export { bossBoxForStage, blueBoxes } from "../../../shared/chest-boxes";

interface HeroRecord {
  key: number;
  name: string;
  classType: string;
}

interface SkillRecord {
  key: number;
  name: string | null;
  names: Record<string, string> | null;
}

interface StageRecord {
  key: number;
  name: string;
  names: Record<string, string> | null;
  act: number;
  stageNo: number;
  difficulty?: string;
  bossDrop?: { itemKey: number; rate: number } | null;
  /** Weighted spawn table (monster keys are strings in the datamine output). */
  monsters?: { monster: string; weight: number }[];
  bossMonsterKey?: number | null;
}

const heroes = heroesData as HeroRecord[];
const skills = skillsData as SkillRecord[];
const stages = stagesData as StageRecord[];

export const heroMap = new Map<number, HeroRecord>(heroes.map((h) => [h.key, h]));
export const skillMap = new Map<number, SkillRecord>(skills.map((s) => [s.key, s]));
export const stageMap = new Map<number, StageRecord>(stages.map((s) => [s.key, s]));

export function heroName(key: number): string {
  return heroMap.get(key)?.name ?? `Hero ${key}`;
}

export function skillName(key: number): string {
  const s = skillMap.get(key);
  if (!s) return `Skill ${key}`;
  return s.names?.["en-us"] ?? s.name ?? `Skill ${key}`;
}

export function stageName(key: number): string {
  const s = stageMap.get(key);
  if (!s) return `Stage ${key}`;
  return s.names?.["en-us"] ?? s.name ?? `Stage ${key}`;
}

// Baked from the reader's StatType(IntEnum) in config/offsets.py (~line 255).
// The runs.jsonl mods carry resolved stat names, but the top-level hero.stats
// dict is keyed by stat id only, so we resolve it here.
const STAT_NAMES: Record<number, string> = {
  0: "None",
  1: "AttackDamage",
  2: "AttackSpeed",
  3: "CriticalChance",
  4: "CriticalDamage",
  5: "MaxHp",
  6: "Armor",
  7: "MovementSpeed",
  8: "AreaOfEffect",
  9: "BaseAttackCountReduction",
  10: "CooldownReduction",
  11: "SkillRangeExpansion",
  12: "FireResistance",
  13: "ColdResistance",
  14: "LightningResistance",
  15: "ChaosResistance",
  16: "DodgeChance",
  17: "BlockChance",
  18: "MaxDodgeChance",
  19: "MaxBlockChance",
  20: "Multistrike",
  21: "HpLeech",
  22: "ProjectileCount",
  23: "HpRegenPerSec",
  24: "PhysicalDamagePercent",
  25: "FireDamagePercent",
  26: "ColdDamagePercent",
  27: "LightningDamagePercent",
  28: "ChaosDamagePercent",
  29: "MaxFireResistance",
  30: "MaxColdResistance",
  31: "MaxLightningResistance",
  32: "MaxChaosResistance",
  33: "AddHpPerHit",
  34: "DamageReduction",
  35: "PhysicalDamageReduction",
  36: "FireDamageReduction",
  37: "ColdDamageReduction",
  38: "LightningDamageReduction",
  39: "ChaosDamageReduction",
  40: "DamageAbsorption",
  41: "DamageAddition",
  42: "PhysicalDamageAddition",
  43: "FireDamageAddition",
  44: "ColdDamageAddition",
  45: "LightningDamageAddition",
  46: "ChaosDamageAddition",
  47: "IncreaseExpAmount",
  48: "AdditionalExp",
  49: "CastSpeed",
  50: "SkillHealIncrease",
  51: "SkillDurationIncrease",
  52: "AllElementalResistance",
  53: "IncreaseProjectileDamage",
  54: "IncreaseMeleeDamage",
  55: "IncreaseAreaOfEffectDamage",
  56: "IncreaseSummonDamage",
  57: "IncreaseProjectileSpeed",
  58: "AddHpPerKill",
  59: "AddAllSkillLevel",
  60: "ElementalBlockChance",
  61: "ElementalDodgeChance",
  62: "MaxElementalBlockChance",
  63: "MaxElementalDodgeChance",
};

export function statName(id: number): string {
  return STAT_NAMES[id] ?? `stat${id}`;
}

// Slim itemKey -> display name, generated by scripts/sync-data.mjs from data/items.json.
const itemNameMap = itemsMinData as Record<string, string>;

export function itemName(key: number | null | undefined): string | null {
  if (key == null) return null;
  return itemNameMap[String(key)] ?? null;
}

// Hero idle animation, copied by sync-data into the renderer's public dir
// (web/public/sprites/anim/heroes/<key>.gif -> public/heroes/Hero_<key>.gif).
// Transparent background, ~33-40 x 31 px. Path is relative to index.html so it
// resolves under both the dev server and file:// in production.
export function heroSprite(heroKey: number): string | null {
  return heroMap.has(heroKey) ? `heroes/Hero_${heroKey}.gif` : null;
}

// box_key (GetBoxLog, a STAGEBOX item key) -> sprite basename, generated by
// scripts/sync-data.mjs from data/items.json. All chests of a tier share one icon
// (910*->Item_910011 common, 920*->Item_920011 stage boss, 930*->Item_930011 act boss).
const chestIconMap = chestsMinData as Record<string, string>;

// Chest drop sprite, copied by sync-data into the renderer's public dir
// (web/public/sprites/<icon>.png -> public/sprites/<icon>.png). Path is relative to
// index.html so it resolves under both the dev server and file:// in production.
// Returns null for an unmapped box_key (e.g. a chest added before the next data sync).
export function chestSprite(boxKey: number): string | null {
  const icon = chestIconMap[String(boxKey)];
  return icon ? `sprites/${icon}.png` : null;
}

// ── Blue-chest cooldown helpers (#265) ──────────────────────────────────────
// Everything a cooldown card needs is DERIVED from a stageKey here (the engine only stores
// stageKey + dropAt), so this file stays the single source of chest/stage facts.

/** Title-cased difficulty for a stage ("NORMAL" -> "Normal"), matching the mode-badge keys
 *  in format.ts. Null when the stage (or its difficulty) is unknown. */
export function stageDifficulty(key: number): string | null {
  const d = stageMap.get(key)?.difficulty;
  if (!d) return null;
  return d.charAt(0) + d.slice(1).toLowerCase();
}

/** Compact stage code "act-stageNo" (e.g. "2-1"), the in-game shorthand. Null if unknown. */
export function stageCode(key: number): string | null {
  const s = stageMap.get(key);
  return s ? `${s.act}-${s.stageNo}` : null;
}

/** The blue-chest BASE drop rate for a stage (game per-mille `bossDrop.rate`), or null if
 *  unmapped. Base only — rune/pet "chest drop chance" bonuses aren't in any reader data. */
export function bossBoxRate(key: number): number | null {
  return stageMap.get(key)?.bossDrop?.rate ?? null;
}

/** Game `rate` (per-mille) → percent string. 8 → "0.8%", 150 → "15%", 1000 → "100%". */
export function formatDropRate(rate: number): string {
  return `${rate / 10}%`;
}

// box key -> the stageKeys whose blue chest IS that box (one box drops across several stages).
const stagesByBoxMap = new Map<number, number[]>();
for (const s of stages) {
  const box = s.bossDrop?.itemKey;
  if (box == null) continue;
  const list = stagesByBoxMap.get(box);
  if (list) list.push(s.key);
  else stagesByBoxMap.set(box, [s.key]);
}

/** Stage keys that drop the given blue-chest box (i.e. the same chest level), in data order. */
export function stagesByBox(boxKey: number): number[] {
  return stagesByBoxMap.get(boxKey) ?? [];
}

/** Chest level for a box ("Stage Boss Box Lv80" -> 80). Delegates to the shared parser so the
 *  card and the main-process notification show the same level. */
export function chestLevel(boxKey: number): number | null {
  return boxLevel(boxKey);
}

/** The highest-base-rate stage that drops this box — the best farm spot, used for the card's
 *  headline rate and the "open stage" link (a route placeholder has no origin stage of its own). */
export function boxBestStage(boxKey: number | null | undefined): number | null {
  if (boxKey == null) return null;
  let best: number | null = null;
  let bestRate = -1;
  for (const k of stagesByBox(boxKey)) {
    const r = bossBoxRate(k) ?? -1;
    if (r > bestRate) {
      bestRate = r;
      best = k;
    }
  }
  return best;
}

// --- Blue box (Stage Boss Box) cross-mode drop spots -------------------------
// For a blue box, WHERE it drops: per mode, the stage ranges grouped by BASE rate
// ("first~last"). Feeds the cooldown card's "spots" row. Rune/pet "chest chance"
// bonuses aren't in any reader data, so this is BASE rate only.

const MODE_FROM_DIFFICULTY: Record<string, string> = {
  NORMAL: "Normal",
  NIGHTMARE: "Nightmare",
  HELL: "Hell",
  TORMENT: "Torment",
};
const MODE_RANK: Record<string, number> = { Normal: 0, Nightmare: 1, Hell: 2, Torment: 3 };

/** One stage-range at one rate, e.g. { range: "3-5~3-9", pct: "15%" }. */
export interface BlueBoxSegment {
  range: string;
  rate: number;
  pct: string;
}
/** All spots for the blue box within one mode, highest-rate range first. */
export interface BlueBoxMode {
  mode: string;
  segments: BlueBoxSegment[];
}

/** Every mode/stage a blue box drops at, grouped by rate into `first~last` ranges and ordered
 *  Normal→Torment. Null when the key isn't a blue box (e.g. an act-boss box → 930xxx). Keyed by
 *  box (not stage) since a cooldown card represents the chest level, not one stage. */
export function blueBoxSpotsForBox(boxKey: number | null | undefined): BlueBoxMode[] | null {
  if (boxKey == null || boxKey < 920000 || boxKey >= 930000) return null; // blue box only

  // Reuse the prebuilt box→stages index instead of re-scanning all stages.
  const byMode = new Map<string, { act: number; stageNo: number; rate: number }[]>();
  for (const k of stagesByBox(boxKey)) {
    const s = stageMap.get(k);
    if (s?.bossDrop?.rate == null || !s.difficulty) continue;
    const mode = MODE_FROM_DIFFICULTY[s.difficulty] ?? s.difficulty;
    let arr = byMode.get(mode);
    if (!arr) byMode.set(mode, (arr = []));
    arr.push({ act: s.act, stageNo: s.stageNo, rate: s.bossDrop.rate });
  }
  if (byMode.size === 0) return null;

  const modes: BlueBoxMode[] = [];
  for (const [mode, spots] of byMode) {
    spots.sort((a, b) => a.act - b.act || a.stageNo - b.stageNo);
    // Rates fall monotonically with depth, so each distinct rate is a contiguous
    // stage range — group by rate, highest first, and collapse to first~last.
    const byRate = new Map<number, string[]>();
    for (const sp of spots) {
      let g = byRate.get(sp.rate);
      if (!g) byRate.set(sp.rate, (g = []));
      g.push(`${sp.act}-${sp.stageNo}`);
    }
    const segments: BlueBoxSegment[] = [...byRate.entries()]
      .sort((a, b) => b[0] - a[0])
      .map(([rate, sts]) => ({
        range: sts[0] === sts[sts.length - 1] ? sts[0] : `${sts[0]}~${sts[sts.length - 1]}`,
        rate,
        pct: formatDropRate(rate),
      }));
    modes.push({ mode, segments });
  }
  modes.sort((a, b) => (MODE_RANK[a.mode] ?? 9) - (MODE_RANK[b.mode] ?? 9));
  return modes;
}
