"""build.py — reads the hero's BUILD: equips/mods/skills (from the save) + the 64 live
FINAL stats (id-only) + the LIVE deployed party identity (heroKeys from StageManager.HeroList;
level/exp read LIVE by decoding the ACTk cipher in place since 1.00.20 — see read_live_party).
Mirrors the monolith.

The 64 stats come out keyed by statId int (id-only; the front resolves the name). The
item/mod/class labels are still filled in (via the offsets enums) so the output matches
the monolith byte-for-byte at cutover; dropping them is a future schema-bump."""

import json
import os
import struct

from config.offsets import (HeroRuntime, StatsHolder, Dict, DictFloat, Array, List, Unit,
                            StageManager, HeroInfoData, HeroSaveData, PlayerSaveData,
                            AttributeSaveData, ItemSaveData, ItemEnchant, name_map,
                            EItemParts, EGradeType, EEquipClassType, ERecipeType, StatType,
                            RuneSaveData, InventorySaveData, StashSaveData)
from game import obscured
from shared.utils import resource_path

_PARTS = name_map(EItemParts)
_GRADE = name_map(EGradeType)
_CLAZZ = name_map(EEquipClassType)
_RECIPE = name_map(ERecipeType)
_STAT = name_map(StatType)

# Sentinel itemKey for an equipped slot whose handle (uniqueId) couldn't be resolved to an item.
# A real itemKey is a positive int and an EMPTY slot is omitted entirely, so -1 unambiguously means
# "equipped but unknown" — the front renders it as a clear "unknown" in that slot. The ingest schema
# (@tbh/shared build-payload: `itemKey: z.number().int().nullable()`) accepts it as-is.
UNKNOWN_ITEM_KEY = -1

_SKILL_ATTR = None
_PASSIVE_KEYS = None


def skill_attr_map():
    """{skillKey: attributeKey} loaded once from config/skill_attr_map.json (generated by
    scripts/gen_skill_attr_map.py from the skill-tree). Bridges the EQUIPPED skill
    (skillKey) to the tree node (attributeKey) where the invested level lives. Via resource_path
    -> works in source AND frozen (PyInstaller). {} if the resource is missing."""
    global _SKILL_ATTR
    if _SKILL_ATTR is None:
        try:
            with open(resource_path(os.path.join("config", "skill_attr_map.json")),
                      encoding="utf-8") as f:
                _SKILL_ATTR = {int(k): int(v) for k, v in json.load(f).items()}
        except Exception:
            _SKILL_ATTR = {}
    return _SKILL_ATTR


def passive_skill_keys():
    """set{attributeKey} of ALL PASSIVE skills (config/passive_skill_keys.json, generated by
    scripts/gen_skill_attr_map.py). A passive is NOT equipped (doesn't appear in equippedSKillKey) —
    it lives only in the tree, and its attributeKey IS the skill's identity. The reader includes the
    ones the hero invested in (intersection with read_attribute_levels). set() if the resource is missing."""
    global _PASSIVE_KEYS
    if _PASSIVE_KEYS is None:
        try:
            with open(resource_path(os.path.join("config", "passive_skill_keys.json")),
                      encoding="utf-8") as f:
                _PASSIVE_KEYS = {int(k) for k in json.load(f)}
        except Exception:
            _PASSIVE_KEYS = set()
    return _PASSIVE_KEYS


def read_attribute_levels(reader, psd):
    """{attributeKey: level} from the invested skills/passives tree (PlayerSaveData.attributeSaveDatas
    @0x40; AttributeSaveData{Key@0x10, Level@0x14}). Source of each equipped skill's level. {} on failure."""
    res = {}
    if not psd:
        return res
    try:
        for a in reader.list_iter(reader.rptr(psd + PlayerSaveData.ATTRIBUTES)):
            k = reader.ri32(a + AttributeSaveData.KEY)
            if k is None:
                continue
            lv = reader.ri32(a + AttributeSaveData.LEVEL)
            if lv is not None:
                res[k] = lv
    except Exception:
        return {}
    return res


def _iter_party_slots(reader, sm, hero_cat=None):
    """Yields (slot, heroKey, uf) for each VALID deployed hero in StageManager.HeroList — the
    SHARED walk behind read_live_party AND read_party_slots, so membership, the ghost discriminator
    and the slot index are defined in ONE place; pick<->read<->slot agree by construction (the
    1.00.13 invariant — see [[invariants/party-live-resolution]]).

    `slot` is the hero's index in the fixed 3-slot formation array: empty slots are null and skipped,
    so the index IS the in-game formation position (0/1/2, gaps included; verified live — HeroList
    len=3, a solo hero sits at its own slot with the others null). GHOST discriminator: a real deployed
    hero resolves a class in `hero_cat`; a ghost carries a stale/garbage key that doesn't
    (hero_cat=None -> heroKey-plausibility only). NEVER raises -> yields nothing on any failure."""
    try:
        if not sm:
            return
        hl = reader.rptr(sm + StageManager.HERO_LIST)
        if not hl:
            return
        n = reader.ri32(hl + Array.MAX_LENGTH)
        if n is None or not (0 < n <= 12):
            return
        for i in range(n):
            h = reader.rptr(hl + Array.DATA + i * 8)
            if not h:
                continue
            uf = reader.rptr(h + Unit.CACHE)
            if not uf:
                continue
            hi = reader.rptr(uf + HeroRuntime.INFO)
            hk = reader.ri32(hi + HeroInfoData.HERO_KEY) if hi else None
            if hk is None or not (0 < hk < 10_000_000):
                continue
            if hero_cat is not None and hk not in hero_cat:
                continue
            yield i, hk, uf
    except Exception:
        return


def read_live_party(reader, sm, hero_cat=None, save_heroes=None):
    """{heroKey: (level, exp)} for the LIVE DEPLOYED party (StageManager.HeroList). The party
    IDENTITY (which heroKeys are on the field) AND the per-hero level/exp are all read LIVE.
    Never raises -> {} on any failure.

    1.00.20 — level/exp are decoded from the ACTk cipher IN PLACE. Through 1.00.19 the live level/exp
    were the ACTk `fakeValue` PLAIN decoys (@ base+0xC of the ObscuredInt/Float). In 1.00.20 the
    recompile KILLED those decoys build-wide (they read 0); the real live values stayed in the cipher
    (hiddenValue @ base+0x4, currentCryptoKey @ base+0x8). Rather than degrade to the lagging save (the
    per-run save delta jumps ~2× — the bug players reported), we RECOVER the live values by decoding the
    cipher read-only (game/obscured.py — algorithm read from the binary, not guessed; ObscuredInt level =
    (hidden-key)^key, ObscuredFloat xp = float(key ^ byteswap(hidden))). The key is read live each tick
    (handles ACTk rotation). LEVEL falls back to the save on an unreadable cipher; EXP stays None on a bad
    read so the xp chain degrades honestly ([[invariants/metric-fallback-chains]] rule 2), never the
    roster. The decode is gated by the validate_live oracle — see [[invariants/obscured-data-offlimits]].

    Ghost discriminator (replaces the dead `lvl>0` filter). The scan/backref returns torn-down/template
    StageManager 'ghosts' alongside the live carrier ([[invariants/instance-selection]] family). The
    old discriminator — a real heroKey but `lvl=0` — relied on the now-dead live level. The new, name-
    free one: the deployed heroKey must resolve a REAL class in `hero_cat` (the 6 hero classes; a ghost
    carries a stale/garbage key that isn't a catalog hero). Verified in 1.00.20: among ALL StageManager
    instances ONLY the deployed ones carry a catalog heroKey (no heroKey-bearing ghosts). hero_cat=None
    -> heroKey-plausibility only (diagnostic callers that just want any live StageManager address).

    pick<->read AGREEMENT (the 1.00.13 invariant): the IDENTITY gate here (heroKey + hero_cat) is the
    SAME validation pick_live_sm uses (it calls this); save_heroes only FILLS the level/exp, never gates
    — so pick and read never disagree on which slot is a carrier."""
    res = {}
    try:
        for _slot, hk, uf in _iter_party_slots(reader, sm, hero_cat):
            # LEVEL + EXP read LIVE by decoding the ACTk cipher in place (the +0xC decoy died in
            # 1.00.20). game/obscured.py reimplements the decode read from the binary. LEVEL falls back
            # to the save snapshot on an unreadable/implausible cipher (stable, context only). EXP stays
            # None on a bad read — NEVER the stale save exp — so close_run degrades to the per-hero save
            # delta honestly ([[invariants/metric-fallback-chains]] rule 2), instead of reporting save as
            # live. The party IDENTITY (which slots count) is the shared _iter_party_slots gate.
            lvl = obscured.decode_obscured_int(reader.ru32(uf + HeroRuntime.LEVEL_HIDDEN),
                                               reader.ru32(uf + HeroRuntime.LEVEL_KEY))
            if lvl is None or not (0 < lvl <= 200):
                lvl = (save_heroes or {}).get(hk, (None, None))[0]
            exp = obscured.decode_obscured_float(reader.ru32(uf + HeroRuntime.EXP_HIDDEN),
                                                 reader.ru32(uf + HeroRuntime.EXP_KEY))
            res[hk] = (lvl, exp)
    except Exception:
        return {}
    return res


def read_party_slots(reader, sm, hero_cat=None):
    """{heroKey: slot} for the LIVE DEPLOYED party — `slot` = the hero's FORMATION position (its
    index in StageManager.HeroList; empty slots are null, so the index IS the in-game position
    0/1/2, gaps included). Shares membership + the ghost discriminator with read_live_party (the
    same _iter_party_slots), so the slot map and the party never disagree. The run record carries
    this per hero so the team's in-game order/position survives to the app and the leaderboard — it
    was previously LOST (heroes came out in SAVE-ROSTER order and the HeroList slot index was
    discarded). NEVER raises -> {}."""
    return {hk: slot for slot, hk, _uf in _iter_party_slots(reader, sm, hero_cat)}


def _raw_hero_list(reader, sm):
    """RAW HeroList (hk, lvl, exp) per slot, WITHOUT read_live_party's validity filter — just for
    diagnostics (describe_sm_candidates), to see WHY an instance is a ghost (e.g. a non-catalog hk).
    lvl/exp are the DEAD ACTk decoy (LEVEL_FAKE/EXP_FAKE read 0 since 1.00.20) — kept only so the raw
    sample still shows what those offsets hold; the discriminator is now the heroKey, not lvl.
    Never-raises -> [] on any failure."""
    out = []
    try:
        if not sm:
            return out
        hl = reader.rptr(sm + StageManager.HERO_LIST)
        if not hl:
            return out
        n = reader.ri32(hl + Array.MAX_LENGTH)
        if n is None or not (0 < n <= 12):
            return out
        for i in range(n):
            h = reader.rptr(hl + Array.DATA + i * 8)
            uf = reader.rptr(h + Unit.CACHE) if h else None
            hi = reader.rptr(uf + HeroRuntime.INFO) if uf else None
            hk = reader.ri32(hi + HeroInfoData.HERO_KEY) if hi else None
            lvl = reader.ri32(uf + HeroRuntime.LEVEL_FAKE) if uf else None
            exp = reader.rf32(uf + HeroRuntime.EXP_FAKE) if uf else None
            out.append((hk, lvl, exp))
    except Exception:
        return out
    return out


def describe_sm_candidates(reader, sm_list, picked, hero_cat=None):
    """Diagnostics for the StageManager pick (for the reader-diag.log infra log). Returns a dict:
      total      number of candidates (StageManager instances from the scan/backref)
      hk_accept  how many have >=1 plausible heroKey (0<hk<10M) = the loosest universe
      carriers   how many are a REAL carrier (non-empty read_live_party) = what the pick accepts
      picked     chosen address (or None)
      ghosts     up to 5 samples (addr, raw heroes) of hk_accept-but-NOT-carrier (a non-catalog heroKey)
    `hk_accept > carriers` flags ghosts in the loose universe (heroKey-bearing but not catalog heroes);
    `carriers == 0` with the run in combat = the carrier wasn't even captured by the scan (rare case, H4).
    Passes `hero_cat` through so the carrier test uses the SAME (catalog) discriminator the pick uses.
    Pure read, never-raises."""
    hk_accept, carriers, ghosts = 0, 0, []
    try:
        for a in (sm_list or []):
            heroes = _raw_hero_list(reader, a)
            if not any(hk is not None and 0 < hk < 10_000_000 for hk, _, _ in heroes):
                continue
            hk_accept += 1
            if read_live_party(reader, a, hero_cat):
                carriers += 1
            elif len(ghosts) < 5:
                ghosts.append((a, heroes[:6]))
    except Exception:
        pass
    return {"total": len(sm_list or []), "hk_accept": hk_accept,
            "carriers": carriers, "picked": picked, "ghosts": ghosts}


def hero_in_run(hero_key, live_keys):
    """Does the hero make it into the run artifact? ONLY if it's in the LIVE party (`live_keys` =
    StageManager.HeroList ∪ party_seen) — the AUTHORITATIVE source. WITHOUT a live party (`live_keys`
    empty = sm null the WHOLE run), the run emits NO hero at all: the caller marks `heroes` as `err`
    in the envelope ("party live off") and the converter seals the run `degraded` (doesn't make it to
    the leaderboard; shows in the app, flagged). NEVER the raw save roster nor a proxy-guess (e.g.
    xp>0 would include a hero that only earned idle xp, re-introducing the bug). Pure/testable."""
    return bool(live_keys) and hero_key in live_keys


def order_party_by_slot(heroes):
    """Stable-sort the run's heroes by their formation `slot` (0/1/2) so the run record emits the
    party in IN-GAME FORMATION order — it used to come out in SAVE-ROSTER order (the order
    PlayerSaveData.HEROES happened to iterate), with the live HeroList slot index discarded. A hero
    with no resolved slot (rare: included via a degraded read) trails, keeping its relative order.
    Pure/testable, mirrors hero_in_run."""
    return sorted(heroes, key=lambda h: (h.get("slot") is None, h.get("slot") or 0))


def read_stats_dict(reader, uf):
    """64 live FINAL stats: uf->xd->bets = Dict<StatType,float> (DictFloat). id-only:
    {statId int: value}. {} on failure."""
    try:
        xd = reader.rptr(uf + HeroRuntime.STATS_HOLDER)
        d = reader.rptr(xd + StatsHolder.FINAL_STATS) if xd else None
        if not d:
            return {}
        ent = reader.rptr(d + Dict.ENTRIES)
        n = reader.ri32(ent + Array.MAX_LENGTH) if ent else None
        if n is None or not (0 < n <= 512):
            return {}
        raw = reader.read(ent + Array.DATA, n * DictFloat.STRIDE)
        if not raw or len(raw) < n * DictFloat.STRIDE:
            return {}
        out = {}
        for i in range(n):
            o = i * DictFloat.STRIDE
            if struct.unpack_from("<i", raw, o + DictFloat.HASH)[0] < 0:   # free slot
                continue
            key = struct.unpack_from("<i", raw, o + DictFloat.KEY)[0]
            val = struct.unpack_from("<f", raw, o + DictFloat.VALUE)[0]
            out[key] = round(val, 4)
        return out
    except Exception:
        return {}


def read_live_stats_by_hero(reader, sm):
    """{heroKey: {statId: value}} of the 64 live FINAL stats for the deployed party."""
    res = {}
    try:
        if not sm:
            return res
        hl = reader.rptr(sm + StageManager.HERO_LIST)
        n = reader.ri32(hl + Array.MAX_LENGTH) if hl else None
        if n is None or not (0 < n <= 12):
            return res
        for i in range(n):
            h = reader.rptr(hl + Array.DATA + i * 8)
            uf = reader.rptr(h + Unit.CACHE) if h else None
            hi = reader.rptr(uf + HeroRuntime.INFO) if uf else None
            hk = reader.ri32(hi + HeroInfoData.HERO_KEY) if hi else None
            if hk is None or not (0 < hk < 10_000_000):
                continue
            st = read_stats_dict(reader, uf)
            if st:
                res[hk] = st
    except Exception:
        return {}
    return res


def read_mods(reader, item_addr):
    """EnchantData[] (struct stride 0x1C) -> real mods (skips empty slots)."""
    arr = reader.rptr(item_addr + ItemSaveData.ENCHANT_DATA)
    if not arr:
        return []
    ln = reader.ri32(arr + Array.MAX_LENGTH)
    if ln is None or ln < 0 or ln > 64:
        return []
    res = []
    for i in range(ln):
        b = arr + Array.DATA + i * ItemEnchant.STRIDE
        st = reader.ri32(b + ItemEnchant.STAT_TYPE)
        val = reader.ri32(b + ItemEnchant.VALUE)
        if (not st) and (not val):
            continue  # empty slot
        rc = reader.ri32(b + ItemEnchant.RECIPE)
        res.append({"recipeId": rc, "recipe": _RECIPE.get(rc, f"r{rc}"),
                    "statId": st, "stat": _STAT.get(st, f"stat{st}"),
                    "value": val, "tier": reader.ri32(b + ItemEnchant.TIER)})
    return res


def read_build(reader, psd, item_cat, hero_cat):
    """Build snapshot per played hero: class/level/exp + equipped items
    (slot/rarity/level/uniqueId) with mods + skills [{key, lv}].

    The `skills` array carries equipped ACTIVES AND invested PASSIVES, each with a level (lv):
    - ACTIVE: the EQUIPPED skill (equippedSKillKey). skillKey -> attributeKey (skill_attr_map)
      -> AttributeSaveData.Level. key = skillKey. lv=None when it's not a known ACTIVESKILL node
      (e.g. the innate skill, outside the tree) or there's no invested level.
    - PASSIVE: an invested PASSIVESKILL node. key == attributeKey (== refKey for passives); lv
      straight from attr_levels. Only the ones the hero has in the tree.
    `skillLevels` (the FULL tree by attributeKey) runs in parallel while the web migrates
    to consuming the `skills` array."""
    out = []
    if not psd:
        return out
    attr_levels = read_attribute_levels(reader, psd)
    skill_attr = skill_attr_map()
    passive_keys = passive_skill_keys()
    uid2item = {}
    for a in reader.list_iter(reader.rptr(psd + PlayerSaveData.ITEMS)):
        uid = reader.ru64(a + ItemSaveData.UNIQUE_ID)
        if uid:
            uid2item[uid] = a
    for h in reader.list_iter(reader.rptr(psd + PlayerSaveData.HEROES), cap=200):
        hk = reader.ri32(h + HeroSaveData.HERO_KEY)
        lvl = reader.ri32(h + HeroSaveData.LEVEL)
        exp = reader.rf32(h + HeroSaveData.EXP)
        if hk is None or lvl is None:
            continue
        if not (lvl > 1 or (exp or 0) > 0):
            continue
        cls = hero_cat.get(hk)
        items = []
        for pos, uid in enumerate(reader.arr_u64(reader.rptr(h + HeroSaveData.EQUIPPED_ITEMS))):
            if not uid:
                continue                                  # uniqueId 0 = an honestly-empty slot
            it = uid2item.get(uid)
            if not it:
                # The equipped handle (uniqueId) isn't in itemSaveDatas, so we can't name the item.
                # DON'T silently drop it (NOT-READ != READ-ZERO): emit it with the UNKNOWN_ITEM_KEY
                # sentinel so the front renders a clear "unknown" in that slot instead of a
                # phantom-empty one. equippedItemIds is SLOT-INDEXED (array pos i -> EItemParts i+1,
                # confirmed live across all 6 classes), so the slot is known even when the item is not.
                pslot = pos + 1
                items.append({"slot": _PARTS.get(pslot, "?"),
                              "slotId": pslot if pslot in _PARTS else None,
                              "grade": "?", "gradeId": None, "itemKey": UNKNOWN_ITEM_KEY,
                              "uniqueId": str(uid), "level": None, "mods": []})
                continue
            ik = reader.ri32(it + ItemSaveData.ITEM_KEY)
            grade, parts, ilvl = item_cat.get(ik, (None, None, None))
            items.append({"slot": _PARTS.get(parts, "?"), "slotId": parts,
                          "grade": _GRADE.get(grade, "?"), "gradeId": grade,
                          "itemKey": ik, "uniqueId": str(uid), "level": ilvl,
                          "mods": read_mods(reader, it)})
        # `skills` = equipped ACTIVES (key = skillKey) + invested PASSIVES (key = attributeKey
        # == refKey), each with lv. attr_levels is account-wide and the attributeKeys are
        # hero-prefixed (a // 1000 == heroKey) -> filter for this hero.
        skills = [{"key": k, "lv": attr_levels.get(skill_attr.get(k))}
                  for k in reader.arr_i32(reader.rptr(h + HeroSaveData.EQUIPPED_SKILLS)) if k]
        skills += [{"key": a, "lv": lv}
                   for a, lv in sorted(attr_levels.items())
                   if lv and lv > 0 and a // 1000 == hk and a in passive_keys]
        # skillLevels: the FULL invested tree by attributeKey. Redundant with `skills` on
        # purpose (temporary): the web still consumes this shape and migrates to the array later.
        skill_levels = {str(a): lv for a, lv in attr_levels.items()
                        if lv and lv > 0 and a // 1000 == hk}
        out.append({"heroKey": hk, "class": _CLAZZ.get(cls, "?"), "classId": cls,
                    "level": lvl, "exp": round(exp or 0.0, 2), "items": items,
                    "skills": skills, "skillLevels": skill_levels})
    return out


def _item_view(reader, it, item_cat):
    """1 save item -> RAW dict (itemKey/rarity/slot/level/uniqueId + mods). None if itemKey is unreadable.
    Same shape as the equipped item in read_build (the app resolves name/sprite by itemKey)."""
    ik = reader.ri32(it + ItemSaveData.ITEM_KEY)
    if ik is None:
        return None
    grade, parts, ilvl = item_cat.get(ik, (None, None, None))
    return {"itemKey": ik, "uniqueId": str(reader.ru64(it + ItemSaveData.UNIQUE_ID) or 0),
            "slotId": parts, "gradeId": grade, "level": ilvl, "mods": read_mods(reader, it)}


def _list_or_none(reader, list_obj, cap):
    """(Non-null) pointers from a List<T>, DISTINGUISHING not-read (None) from empty ([]) — so the
    caller emits `err` instead of a SILENT `ok([])` (envelope invariant: NOT-READ != READ-ZERO, the
    same rule that killed the gold:0 bug). None if the List isn't structurally readable (size/items
    unreadable or out of range); [] ONLY when size==0 for real. The Reader's `list_ptrs` is NO good
    here: it returns [] in BOTH cases (empty and unreadable), erasing the distinction."""
    if not list_obj:
        return None
    size = reader.ri32(list_obj + List.SIZE)
    if size is None or size < 0 or size > cap:
        return None
    if size == 0:
        return []
    items = reader.rptr(list_obj + List.ITEMS)
    if not items:
        return None
    b = reader.read(items + Array.DATA, size * 8)
    if not b or len(b) < size * 8:
        return None
    return [p for p in struct.unpack(f"<{size}Q", b) if p]


def _read_runes(reader, psd):
    """[{key, level}] of the runes (PlayerSaveData.RUNES). None if the list DIDN'T READ (never a silent [])."""
    try:
        raw = _list_or_none(reader, reader.rptr(psd + PlayerSaveData.RUNES), 5000)
        if raw is None:
            return None
        out = []
        for a in raw:
            k = reader.ri32(a + RuneSaveData.KEY)
            lv = reader.ri32(a + RuneSaveData.LEVEL)
            if k is not None and lv is not None:
                out.append({"key": k, "level": lv})
        return out
    except Exception:
        return None


def _read_slot_items(reader, psd, list_off, uid_off, uid2item, item_cat):
    """Items in the slots (uniqueId -> uid2item -> item). None if the slot list OR the uid2item didn't read
    (-> err, not a silent []). A slot with uniqueId 0 is EMPTY (skipped; doesn't count as a failure)."""
    if uid2item is None:
        return None
    try:
        raw = _list_or_none(reader, reader.rptr(psd + list_off), 100000)
        if raw is None:
            return None
        out = []
        for s in raw:
            uid = reader.ru64(s + uid_off)
            if not uid:
                continue                                   # empty slot (not a failure)
            it = uid2item.get(uid)
            if it:
                v = _item_view(reader, it, item_cat)
                if v:
                    out.append(v)
        return out
    except Exception:
        return None


def read_account_snapshot(reader, psd, item_cat):
    """RAW account portrait at the end of the run (SAVE source): (runes, inventory, stash). Each is a LIST
    when it READ OK (may be [] = genuinely empty), or **None when it DIDN'T READ** — in which case the
    caller emits `err`, NEVER `ok([])` (envelope invariant: not-read != read-zero, the same rule that
    killed gold:0). Don't confuse the two: a new account with no runes = `ok([])`; an offset breaking in a
    patch = `err`.
      - runes:     PlayerSaveData.RUNES (account-wide; matches data/runes.json for drop-rate/wave).
      - inventory: items in the inventory slots (INVENTORY_SLOTS -> uniqueId -> ITEMS).
      - stash:     items in the stash slots (STASH), separate from the inventory.
    A LARGE snapshot by design (written on EVERY run). All PLAIN from the already-open save (no new singleton,
    no Obscured). NEVER-RAISES (each block guarded -> None on failure) so it doesn't take down close_run."""
    if not psd:
        return None, None, None                            # no live save -> all NOT-READ (err)
    runes = _read_runes(reader, psd)
    # uid2item from ITEMS: None if ITEMS didn't read -> inv/stash become err (not a silent []). HIGH cap:
    # materials stack as instances; _list_or_none returns None above the cap (doesn't truncate).
    # Guarded like the sibling blocks (_read_runes/_read_slot_items): the NEVER-RAISES contract can't
    # depend on the Reader never raising — a throw here would kill close_run.
    try:
        items_raw = _list_or_none(reader, reader.rptr(psd + PlayerSaveData.ITEMS), 100000)
        uid2item = None
        if items_raw is not None:
            uid2item = {}
            for it in items_raw:
                uid = reader.ru64(it + ItemSaveData.UNIQUE_ID)
                if uid:
                    uid2item[uid] = it
    except Exception:
        uid2item = None
    inventory = _read_slot_items(reader, psd, PlayerSaveData.INVENTORY_SLOTS,
                                 InventorySaveData.UNIQUE_ID, uid2item, item_cat)
    stash = _read_slot_items(reader, psd, PlayerSaveData.STASH,
                             StashSaveData.UNIQUE_ID, uid2item, item_cat)
    return runes, inventory, stash
