// Stage -> blue-chest box, the chest's true identity. Lives in shared/ because BOTH the main
// process (the cooldown tracker keys cooldowns by box) and the renderer (cards + route picker)
// must derive a box from a stageKey. Built from the synced game data (stages.json) — the same
// source the renderer's game-data.ts reads, so the two never drift.
//
// Why box, not stage: many stages drop the SAME box (the in-game "Stage Boss Box LvNN"), and the
// same box can span difficulties (e.g. Lv65 drops in both Hell and Torment). The box IS the chest
// level, so keying a cooldown by box — not stage — is what makes "one cooldown per chest level,
// independent of stage" correct (the 6 duplicate Lv80 cards collapse to one).

import stagesData from "./data/stages.json";
import itemsMinData from "./data/items-min.json";

interface StageRecord {
  key: number;
  bossDrop?: { itemKey: number; rate: number } | null;
}

// itemKey -> display name, e.g. "920801" -> "Stage Boss Box Lv80" (generated by sync-data).
const itemNameMap = itemsMinData as Record<string, string>;

// A blue (stage-boss) box is a 920xxx STAGEBOX. 910xxx = common (gray), 930xxx = act-boss.
const BLUE_BOX_MIN = 920000;
const BLUE_BOX_MAX = 930000;

/** True when `boxKey` is a blue (stage-boss) box — the only kind this tracker follows. */
export function isBlueBox(boxKey: number | null | undefined): boolean {
  return boxKey != null && boxKey >= BLUE_BOX_MIN && boxKey < BLUE_BOX_MAX;
}

// stageKey -> its boss-drop box key (a 920xxx blue box or a 930xxx act-boss box), absent when the
// stage has no boss drop.
const stageToBox = new Map<number, number>();
for (const s of stagesData as StageRecord[]) {
  const box = s.bossDrop?.itemKey;
  if (box != null) stageToBox.set(s.key, box);
}

/** The boss-drop box key a stage drops (stage.bossDrop.itemKey), or null if none. Generic: may be
 *  a blue box (920xxx) or an act-boss box (930xxx) — callers that only want blue gate with
 *  `isBlueBox`. */
export function bossBoxForStage(stageKey: number | null | undefined): number | null {
  if (stageKey == null) return null;
  return stageToBox.get(stageKey) ?? null;
}

/** Chest level parsed from the box's display name ("Stage Boss Box Lv80" -> 80, "...Box 4" -> 4).
 *  Null when the name is unmapped or carries no trailing number. The single source for the level
 *  shown on a card and spoken in the OS "ready" notification. */
export function boxLevel(boxKey: number | null | undefined): number | null {
  if (boxKey == null) return null;
  const m = itemNameMap[String(boxKey)]?.match(/(\d+)\s*$/);
  return m ? Number(m[1]) : null;
}

// The distinct blue boxes (chest levels), each with its parsed level, sorted by level ASC — the
// route picker's universe (one chip per level). Built once from the stages that drop a blue box.
const BLUE_BOXES: { boxKey: number; level: number | null }[] = (() => {
  const seen = new Set<number>();
  const out: { boxKey: number; level: number | null }[] = [];
  for (const box of stageToBox.values()) {
    if (!isBlueBox(box) || seen.has(box)) continue;
    seen.add(box);
    out.push({ boxKey: box, level: boxLevel(box) });
  }
  return out.sort((a, b) => (a.level ?? 0) - (b.level ?? 0));
})();

/** Every blue-chest box (chest level) the player can pin to a route, sorted by level. */
export function blueBoxes(): { boxKey: number; level: number | null }[] {
  return BLUE_BOXES;
}
